---
- name: Install Docker and configure non-root user on Ubuntu
  hosts: all
  become: yes

  tasks:
    - import_tasks: ../tasks/update-packages.yml

    - name: Install required packages for Docker
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Get system architecture
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Get Ubuntu codename
      shell: . /etc/os-release && echo ${UBUNTU_CODENAME:-$VERSION_CODENAME}
      register: ubuntu_codename
      changed_when: false

    - name: Add Docker repository to Apt sources
      apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        state: present
        filename: docker

    - name: Update apt package list again after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Create Docker group if it doesn't exist
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted
