---
- name: Set up Prometheus/Grafana monitoring stack
  hosts: all
  become: yes

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      failed_when: docker_version.rc != 0
      changed_when: false

    - name: Check if Docker Compose is installed
      command: docker compose version
      register: docker_compose_version
      failed_when: docker_compose_version.rc != 0
      changed_when: false

    - name: Create /home/monitoring directory
      file:
        path: /home/monitoring
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Ensure ownership of /home/monitoring is set
      file:
        path: /home/monitoring
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Clone home-lab-monitoring repository
      git:
        repo: https://github.com/denesbeck/home-lab-monitoring
        dest: /home/monitoring
        depth: 1

    - name: Run git config command to add safe.directory
      command: git config --global --add safe.directory /home/monitoring
      args:
        chdir: /home/monitoring

    - name: Run Docker Compose to start services
      command: docker compose up -d
      args:
        chdir: /home/monitoring
