---
- name: Set up NGINX with SSL and custom configuration
  hosts: all
  become: yes

  vars:
    ssl_country: "US"
    ssl_state: "California"
    ssl_city: "San Francisco"
    ssl_organization: "Home Lab"
    ssl_common_name: "{{ ansible_default_ipv4.address | default('localhost') }}"

  tasks:
    - import_tasks: ../tasks/update-packages.yml

    - name: Install NGINX
      package:
        name: nginx
        state: present

    - name: Check if SSL certificate exists
      stat:
        path: /etc/ssl/certs/nginx-docker.crt
      register: ssl_cert_exists

    - name: Create the self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:4096
        -keyout /etc/ssl/private/nginx-docker.key
        -out /etc/ssl/certs/nginx-docker.crt
        -subj "/C={{ ssl_country }}/ST={{ ssl_state }}/L={{ ssl_city }}/O={{ ssl_organization }}/CN={{ ssl_common_name }}"
      when: not ssl_cert_exists.stat.exists

    - name: Set proper permissions on SSL private key
      file:
        path: /etc/ssl/private/nginx-docker.key
        owner: root
        group: root
        mode: '0600'

    - name: Set proper permissions on SSL certificate
      file:
        path: /etc/ssl/certs/nginx-docker.crt
        owner: root
        group: root
        mode: '0644'

    - name: Check if DH parameters exist
      stat:
        path: /etc/ssl/certs/dhparam.pem
      register: dhparam_exists

    - name: Create Diffie-Hellman group
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
      when: not dhparam_exists.stat.exists

    - name: Set proper permissions on DH parameters
      file:
        path: /etc/ssl/certs/dhparam.pem
        owner: root
        group: root
        mode: '0644'

    - name: Remove default NGINX site config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add custom NGINX config for Docker
      template:
        src: ../config/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/docker.conf

    - name: Restart NGINX service
      service:
        name: nginx
        state: restarted
        enabled: yes
