---
- name: Set up NGINX with SSL and custom configuration
  hosts: all
  become: yes

  tasks:
    - import_tasks: ../tasks/update-packages.yml

    - name: Install NGINX
      package:
        name: nginx
        state: present

    - name: Create the self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:4096
        -keyout /etc/ssl/private/nginx-docker.key
        -out /etc/ssl/certs/nginx-docker.crt
        -subj "/C=US/ST=State/L=City/O=Organization/CN=home-lab"

    - name: Create Diffie-Hellman group
      command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

    - name: Remove default NGINX site config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Add custom NGINX config for Docker
      template:
        src: ../config/nginx.conf.j2
        dest: /etc/nginx/sites-enabled/docker.conf

    - name: Restart NGINX service
      service:
        name: nginx
        state: restarted
        enabled: yes
