- name: Install and configure Samba
  hosts: all
  become: yes
  tasks:
    - import_tasks: ../tasks/update-packages.yml

    - name: Install Samba package
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Create samba group
      group:
        name: smbgroup
        state: present

    - name: Create samba user and group
      user:
        name: smbuser
        group: smbgroup
        state: present
        create_home: false
        shell: /bin/bash

    - import_tasks: ../tasks/generate-password.yml

    - name: Add samba user with generated password
      expect:
        command: smbpasswd -a smbuser
        responses:
          "New SMB password:": "{{ password }}"
          "Retype new SMB password:": "{{ password }}"
      register: smbpasswd_result

    - name: Ensure smbpasswd was successful
      debug:
        msg: "Samba user added with password"
      when: smbpasswd_result.rc == 0
      failed_when: smbpasswd_result.rc != 0

    - name: Backup current smb.conf
      copy:
        src: /etc/samba/smb.conf
        dest: "/etc/samba/smb.conf.bak.{{ ansible_date_time.date | replace('-', '') }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
        remote_src: yes
        backup: yes

    - name: Configure smb.conf with custom settings
      template:
        src: ../config/smb.conf.j2
        dest: /etc/samba/smb.conf
      notify:
        - Restart samba

  handlers:
    - name: Restart samba
      service:
        name: smbd
        state: restarted
