---
- name: Update and upgrade Ubuntu system
  hosts: all
  become: yes
  tasks:
    - import_tasks: ../tasks/update-packages.yml

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        autoremove: yes
